services:
  db:
    image: bitnami/postgresql:16.2.0-debian-12-r15
    environment:
      - POSTGRESQL_USERNAME=strapi
      - POSTGRESQL_PASSWORD=strapi
      - POSTGRESQL_DATABASE=strapi
    ports:
      - 5555:5432
    volumes:
      - postgres_data:/bitnami/postgresql
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  insight:
    image: redis/redisinsight:2.42
    ports:
      - '5540:5540'
    depends_on:
      - redis
volumes:
  postgres_data:

