version: "3.7"
services:
  db:
    image: bitnami/postgresql:15.5.0
    environment:
      - POSTGRESQL_USERNAME=strapi
      - POSTGRESQL_PASSWORD=strapi
      - POSTGRESQL_DATABASE=strapi
    ports:
      - 5555:5432
    volumes:
      - ./postgres-data:/bitnami/postgresql