[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[deploy]
numReplicas = 1
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"
sleepApplication = true
startCommand = "pnpm run start"
