/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import seo from "@strapi-community/plugin-seo/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    seo: seo,
    graphql: graphql,
    "users-permissions": usersPermissions,
  },
});
